{% set name = "pdal_wrench" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PDAL/wrench/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec743a5acd39740e9de4bf1b84c7e7012c1ba9f9da11de2082cc10a357007040

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libpdal-core
    - libgdal-core

test:
  commands:
    - pdal_wrench info https://s3.amazonaws.com/hobu-lidar/autzen-classified.copc.laz


about:
  home: https://github.com/PDAL/wrench
  summary: 'PDAL workflows for processing data'
  description: |
    A collection of utilities and workflows for processing point cloud
    data with PDAL
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://github.com/PDAL/wrench
  dev_url: https://github.com/PDAL/wrench

extra:
  recipe-maintainers:
    - hobu
