schema_version: 1

context:
  name: pdal_wrench
  version: "1.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/PDAL/wrench/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 520538b88a3e24277e81053a52a2b74b217933f8a8a1a151622dd3d97b562cff

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libpdal-core
    - libgdal-core

tests:
  - script:
      - pdal_wrench info https://s3.amazonaws.com/hobu-lidar/autzen-classified.copc.laz

about:
  summary: PDAL workflows for processing data
  description: |
    A collection of utilities and workflows for processing point cloud
    data with PDAL
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://github.com/PDAL/wrench
  repository: https://github.com/PDAL/wrench
  documentation: https://github.com/PDAL/wrench

extra:
  recipe-maintainers:
    - hobu
