schema_version: 1

context:
  name: pdal_wrench
  version: "1.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/PDAL/wrench/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3e05f918622b8fcfd87ed569a8da2d01484b9f97e90839a381479c340d19631b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libpdal-core
    - libgdal-core
    - libzip

tests:
  - script:
      - pdal_wrench info https://s3.amazonaws.com/hobu-lidar/autzen-classified.copc.laz

about:
  summary: PDAL workflows for processing data
  description: |
    A collection of utilities and workflows for processing point cloud
    data with PDAL
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://github.com/PDAL/wrench
  repository: https://github.com/PDAL/wrench
  documentation: https://github.com/PDAL/wrench

extra:
  recipe-maintainers:
    - hobu
